//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataServicesWebApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class Address1
    {
        public Address1()
        {
            this.CustomerAddresses = new HashSet<CustomerAddress1>();
            this.SalesOrderHeaders = new HashSet<SalesOrderHeader1>();
            this.SalesOrderHeaders1 = new HashSet<SalesOrderHeader1>();
        }
    
        public int AddressID { get; set; }
        public string AddressLine1 { get; set; }
        public string AddressLine2 { get; set; }
        public string City { get; set; }
        public string StateProvince { get; set; }
        public string CountryRegion { get; set; }
        public string PostalCode { get; set; }
        public System.Guid rowguid { get; set; }
        public System.DateTime ModifiedDate { get; set; }
    
        public virtual ICollection<CustomerAddress1> CustomerAddresses { get; set; }
        public virtual ICollection<SalesOrderHeader1> SalesOrderHeaders { get; set; }
        public virtual ICollection<SalesOrderHeader1> SalesOrderHeaders1 { get; set; }
    }
}
