//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataServicesWebApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductCategory1
    {
        public ProductCategory1()
        {
            this.Products = new HashSet<Product1>();
            this.ProductCategory11 = new HashSet<ProductCategory1>();
        }
    
        public int ProductCategoryID { get; set; }
        public Nullable<int> ParentProductCategoryID { get; set; }
        public string Name { get; set; }
        public System.Guid rowguid { get; set; }
        public System.DateTime ModifiedDate { get; set; }
    
        public virtual ICollection<Product1> Products { get; set; }
        public virtual ICollection<ProductCategory1> ProductCategory11 { get; set; }
        public virtual ProductCategory1 ProductCategory2 { get; set; }
    }
}
